package pojo;
// Generated 22/11/2017 02:11:49 by Hibernate Tools 4.3.1



/**
 * UsuarioTipoEmergencia generated by hbm2java
 */
public class UsuarioTipoEmergencia  implements java.io.Serializable {


     private UsuarioTipoEmergenciaId id;

    public UsuarioTipoEmergencia() {
    }

    public UsuarioTipoEmergencia(UsuarioTipoEmergenciaId id) {
       this.id = id;
    }
   
    public UsuarioTipoEmergenciaId getId() {
        return this.id;
    }
    
    public void setId(UsuarioTipoEmergenciaId id) {
        this.id = id;
    }




}


