package pojo;
// Generated 22/11/2017 02:11:49 by Hibernate Tools 4.3.1



/**
 * UsuarioTipoEmergenciaId generated by hbm2java
 */
public class UsuarioTipoEmergenciaId  implements java.io.Serializable {


     private int idTpEmergencia;
     private int idUsuario;

    public UsuarioTipoEmergenciaId() {
    }

    public UsuarioTipoEmergenciaId(int idTpEmergencia, int idUsuario) {
       this.idTpEmergencia = idTpEmergencia;
       this.idUsuario = idUsuario;
    }
   
    public int getIdTpEmergencia() {
        return this.idTpEmergencia;
    }
    
    public void setIdTpEmergencia(int idTpEmergencia) {
        this.idTpEmergencia = idTpEmergencia;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsuarioTipoEmergenciaId) ) return false;
		 UsuarioTipoEmergenciaId castOther = ( UsuarioTipoEmergenciaId ) other; 
         
		 return (this.getIdTpEmergencia()==castOther.getIdTpEmergencia())
 && (this.getIdUsuario()==castOther.getIdUsuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTpEmergencia();
         result = 37 * result + this.getIdUsuario();
         return result;
   }   


}


